### ISSUE TITLE
Exceptions encounter

### ISSUE THREAD

**Issue by avalon60** [Akascape/CTkMenuBar#1]
Hi @Akascape. Any ideas?  I can't get the CTkMenuBar to work.

If I use:

`from .lib.CTkMenuBar import *`

I get:

```
/home/clive/PycharmProjects/dccm/venv/bin/python3 /home/clive/PycharmProjects/dccm/dccm.py -m gui 
Traceback (most recent call last):
  File "/home/clive/PycharmProjects/dccm/dccm.py", line 16, in <module>
    import dccm_v as vew
  File "/home/clive/PycharmProjects/dccm/dccm_v.py", line 23, in <module>
    from .lib.CTkMenuBar import *
ImportError: attempted relative import with no known parent package
```

If I use this:

```
from lib.CTkMenuBar import CTkMenuBar

        self.des_menu = CTkMenuBar(master=self, tearoff=0)
        self.config(menu=self.des_menu)
```

I get this:

```
  File "/home/clive/PycharmProjects/dccm/dccm_v.py", line 178, in create_menu
    self.des_menu.add_cascade(label='File', menu=self.file_menu)
  File "/home/clive/PycharmProjects/dccm/lib/CTkMenuBar/menu_bar.py", line 56, in add_cascade
    self.menu_button = customtkinter.CTkButton(self, text=text, fg_color=fg_color,
  File "/home/clive/PycharmProjects/dccm/venv/lib/python3.10/site-packages/customtkinter/windows/widgets/ctk_button.py", line 52, in __init__
    super().__init__(master=master, bg_color=bg_color, width=width, height=height, **kwargs)
  File "/home/clive/PycharmProjects/dccm/venv/lib/python3.10/site-packages/customtkinter/windows/widgets/core_widget_classes/ctk_base_class.py", line 46, in __init__
    check_kwargs_empty(kwargs, raise_error=True)
  File "/home/clive/PycharmProjects/dccm/venv/lib/python3.10/site-packages/customtkinter/windows/widgets/utility/utility_functions.py", line 18, in check_kwargs_empty
    raise ValueError(f"{list(kwargs_dict.keys())} are not supported arguments. Look at the documentation for supported arguments.")
ValueError: ['label', 'menu'] are not supported arguments. Look at the documentation for supported arguments.
```

**Comment by Akascape** [comment]
@avalon60 Please refer the examples

**Comment by avalon60** [comment]
The problem is, that those examples assume that the API is located in its own folder, directly in the top level folder of the project. I want to place it in a lib directory, along with other non PyPi inclusions.
